# Generated by Django 5.2.6 on 2025-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="text_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
