# Generated by Django 5.2.6 on 2025-10-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_uploadedfile_text_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="cleaned_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
