# Generated by Django 5.2.6 on 2025-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_uploadedfile_cleaned_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="extension",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
